### ISSUE TITLE
June and July are the same when you select the month

### ISSUE THREAD

**Issue by RobertoFMBarreto** [FadyFayezYounan/easy_date_timeline#10]
When i select june it assumes as july, so june and july is the same date

**Comment by RobertoFMBarreto** [comment]
It must be something with the odd months because this error appens with February, April, June, August doesnt happen maybe because its current date so it happens with september and november

**Comment by RobertoFMBarreto** [comment]
If i set the initial date to January it works

**Comment by RobertoFMBarreto** [comment]
The problem is with the day 31 of this month, if i set the initial date as day 30 it works just fine

**Comment by FadyFayezYounan** [comment]
Do you mean that when selecting December, it only displays 30 days?

**Comment by RobertoFMBarreto** [comment]
No, yesterday it was the day 31 of august and when i was testing the months were wrong, but only February, April, June, September and November, they where showing as the next month, like November was showing as December, just like another issue that someone sent.

So then i set the date myself to day 30 of august and all the months were wright. Today i tried to replicate the problem and it didn't happen again.

**Comment by FadyFayezYounan** [comment]
Thank you for your note. The issue has been resolved, and an update to the library has been made.

**Comment by RobertoFMBarreto** [comment]
thank you for your speedy resolution
