### ISSUE TITLE
[Feature Request]: Custom DateFormats for HeaderProps

### ISSUE THREAD

**Issue by ghost** [FadyFayezYounan/easy_date_timeline#14]
Instead of 
```
headerProps: EasyHeaderProps(
  selectedDateFormat: SelectedDateFormat.<some value>,
),
```

Changing this to DateFormat of Intl would make it much more flexible.

Currently, am unable to show year in the header.

Ideal case
```
headerProps: EasyHeaderProps(
  selectedDateFormat: DateFormat.yyyy,
),
```

**Comment by FadyFayezYounan** [comment]
Thank you for your feedback. I will provide this feature as soon as possible..

**Comment by FadyFayezYounan** [comment]
this feature is available now ex:
![formatter](https://github.com/FadyFayezYounan/easy_date_timeline/assets/116398331/6ac2ef7a-21ca-42aa-ab8a-52e2f81c85f1)
