### ISSUE TITLE
Year selection issue

### ISSUE THREAD

**Issue by noelsj007** [FadyFayezYounan/easy_date_timeline#15]
There is no controller to select the year this is the key for the calendar but you missed it

**Comment by FadyFayezYounan** [comment]
Yes, you are right. The package has been designed to work only with the given year. To make this modification, this will need some time. However, if you want to select a specific year, you can use the other widget (EasyInfiniteDateTimeLine) that allows you to set the start and end dates. and you can make your own year picker widget and then change the year using the controller.
