### ISSUE TITLE
Its not working on web

### ISSUE THREAD

**Issue by juanccalzadilla** [FadyFayezYounan/easy_date_timeline#19]
Hello! 

Im using this package for mobile and web but in web its not working.

Im not able to swipe, and there is not arrows available to move between days.

any solution available? 

Thanks!!

![image](https://github.com/FadyFayezYounan/easy_date_timeline/assets/78725536/4ca97498-c553-48bb-96f2-72e1c0e56daa)

**Comment by FadyFayezYounan** [comment]
I'm sorry for the late reply. check it now.
