### ISSUE TITLE
How to change year? We can change months but not year

### ISSUE THREAD

**Issue by hadi7khan** [FadyFayezYounan/easy_date_timeline#2]
We must get a calendar dialog where we can switch years and months and selected date will take date month and year based on datechange

**Comment by FadyFayezYounan** [comment]
It is the next step. Please note that this might take a bit of time, but I'll keep you updated on my progress.

**Comment by oscarchuaweiwen-fsd** [comment]
@FadyFayezYounan Hi and sorry to disturb, do you have any upcoming updates on this issue? Hopefully u can add change year functionality soon

**Comment by FadyFayezYounan** [comment]
I'm sorry for the late reply. I've been really busy lately. But to answer your question, I'm already working on adding that feature to the package. I just need a little more time.

**Comment by SaddamMohsen** [comment]
> @oscarchuaweiwen-fsd I'm sorry for the late reply. I've been really busy lately. But to answer your question, I'm already working on adding that feature to the package. and already finished the year picker and i am working now to add month picker, I just need a little more time.

Ok we are waiting for you i hope you do it as soon as you can
before we chang to other package
i love your package and i do not want to change it

**Comment by esodot** [comment]
Hi would love to see the year being part of the picker. Currently facing an issue that once the EasyDateTimeLine has been build I am not able to change the initial date. It remains the first given initaldate even after setState in the parent widget.

**Comment by maulikchak** [comment]
need year picker functionality same as a month picker (dropdown and switcher) also give option on **EasyDateTimeLine** firstDate like **EasyInfiniteDateTimeLine** so we hide past dates

**Comment by Saim22Ahmed** [comment]
@FadyFayezYounan brother can you please update the code with the year picker it would be very helpfull ! Thanks
