### ISSUE TITLE
Dark Mode

### ISSUE THREAD

**Issue by Cimorexave** [FadyFayezYounan/easy_date_timeline#20]
It would be great if the widget supported dark mode colors.

**Comment by FadyFayezYounan** [comment]
I'm sorry for the late reply. the `EasyDateTimeLine` has itemBuilders that allows for full customization of the timeline items. if you have a UI you can reply with image and i can help you achieve what you want

**Comment by Cimorexave** [comment]
no It's alright I did manage to customize it well, was just thinking if it could support native brightness like material widgets. maybe I'll do a pr in the future. amazing package though  👍
