### ISSUE TITLE
Disabled all of previous dates

### ISSUE THREAD

**Issue by hakujaya** [FadyFayezYounan/easy_date_timeline#27]
Is there a way, or props that we can set to completely disabled user to choose previous date than today?

**Comment by FadyFayezYounan** [comment]
here is an example about how to disable previous dates 
![Uploading disabled_dates_example.png…]()

**Comment by FadyFayezYounan** [comment]
@hakujaya here is an example about how to disable previous dates
![disabled_dates_example](https://github.com/FadyFayezYounan/easy_date_timeline/assets/116398331/4dcb357f-09fd-4b31-bd56-9a5b3c9d6524)

**Comment by FadyFayezYounan** [comment]
Hey @hakujaya Since we haven't heard back in a while, I'm going to close this for now. If anything comes up, please feel free to let me know without hesitation.
