### ISSUE TITLE
how to change location of active day

### ISSUE THREAD

**Issue by Akramova99** [FadyFayezYounan/easy_date_timeline#30]
Using the EasyDateTimeLine code brought me a lot of convenience. But the active day, which shows today, is always on the left side. How about making it visible in the middle of the page. Please let me know if there is another way.

**Comment by FadyFayezYounan** [comment]
Hello, @Akramova99! If you are using the EasyInfiniteDateTimeLine widget, there is a parameter called "selectionMode" sets it to "SelectionMode.autoCenter()" this will make the active day always at the center of the screen. However, if you are using EasyDateTimeline  widget, I will work on adding this feature soon.
