### ISSUE TITLE
jumpToFocusDate does not center the focused date correctly

### ISSUE THREAD

**Issue by leonard-palm-blg** [FadyFayezYounan/easy_date_timeline#31]
I am currently experiencing issues with centering the focused date.

I am displaying 5 date Widgets across the whole screen width. The user can change the date from outside of this timeline widget, so I have to use your controller to animate to the updated date. To achieve my date being centered horizontally I currently have to call: 

`controller.animateToDate(next.effectiveTimelineSelectedDate.add(1.days));`

`jumpToFocusDate` does not work either

I don't know why but I think the calculation of the scroll offset somehow does not work correctly.

- The call to "controller.animateToDate" is done after a delay, so the widget should have rendered itself by then
- I have selectionMode set to autoCenter
- The date that I want to animate to is also set in the constructor of EasyInfiniteDateTimeLine via focusDate

**Comment by FadyFayezYounan** [comment]
Can you show me a short video of the problem you're facing so that I can assist you better, or you can try using the latest version of the package, I have updated it and made some enhancements to the auto center scroll behavior.

**Comment by leonard-palm-blg** [comment]
@FadyFayezYounan I am not allowed to share detailed videos or something else from the project.

I have now tried version 1.0.7 and I still have to add one day to have it scroll to the center.

This is the ui code, that will center the selectedDate:

```dart

final EasyInfiniteDateTimelineController controller = EasyInfiniteDateTimelineController();
ref.listen(
  provider,
  (previous, next) async {
    await Future.delayed(const Duration(milliseconds: JUMP_TO_DATE_DELAY_MS));
    controller.jumpToDate(next.effectiveTimelineSelectedDate.add(1.days));
  },
);
...

/// be calculated based on the screen width.
final double dayContainerSize = (MediaQuery.of(context).size.width) / 5;

EasyInfiniteDateTimeLine(
        controller: controller,
        timeLineProps: const EasyTimeLineProps(
          /// Setting Dimens.ONE as [separatorPadding] is important to understand the calculation of [dayContainerSize]
          // ignore: avoid_redundant_argument_values
          separatorPadding: Dimens.ZERO,
          hPadding: Dimens.ZERO,
          // ignore: avoid_redundant_argument_values
          vPadding: Dimens.ZERO,
          margin: verticalPadding16,
        ),
        dayProps: EasyDayProps(
          width: dayContainerSize,
          height: dayContainerSize,
        ),
        itemBuilder: (
          BuildContext context,
          String dayNumber,
          String dayName,
          String monthName,
          DateTime fullDate,
          bool isSelected,
        ) {
          return Padding(
            padding: allPadding4,
            child: Container(
              width: dayContainerSize - Dimens.ONE,
              height: dayContainerSize - Dimens.ONE,
              decoration: isSelected
                  ? BoxDecoration(
                      shape: BoxShape.circle,
                      border: Border.all(
                        color: AppTheme.of(context).colors.purple.color,
                        width: 3.0,
                      ),
                      boxShadow: [
                        BoxShadow(
                          color: AppTheme.of(context).colors.purple.withOpacity(opacity: 0.2).color,
                          blurRadius: Dimens.HALF,
                        ),
                      ],
                    )
                  : null,
              child: Opacity(
                opacity: isSelected ? OpacityValues.FULL : 0.4,
                child: Center(
                  child: Column(
                    mainAxisSize: MainAxisSize.min,
                    children: [
                      AppText(
                        dayNumber,
                        style: AppTheme.of(context).textTheme.textBodyL.copyWith(
                              color: AppTheme.of(context).colors.white,
                            ),
                      ),
                      AppText(
                        fullDate.translatedMonthName.toUpperCase(),
                        style: AppTheme.of(context).textTheme.textBodyS.copyWith(
                              color: AppTheme.of(context).colors.white,
                            ),
                      ),
                    ],
                  ),
                ),
              ),
            ),
          );
        },
        onDateChange: (date) {
          final bool dateChanged = notifier.onDateTapped(date);
          if (dateChanged) {
            controller.animateToDate(date.subtract(2.days));
          }
        },
        locale: LOCALE_GERMAN,
        disabledDates: disabledDates,
        firstDate: firstDate,
        focusDate: selectedDate,
        lastDate: lastDate,
        showTimelineHeader: false,
      ),
```

**Comment by FadyFayezYounan** [comment]
@leonard-palm-blg , I apologize for the late reply. I understand your problem now. You have 5 days and you want to make the active day autoCentered, However, it won't work because there is not enough space inside the list to scroll. This is the approach used by the package. As you mentioned, when you added a sixth day, it started working with you because there was enough space available in that case. to solve this in your case, you can change the `SelectionMode ` from `SelectionMode.autoCenter()` to ` SelectionMode.none()`.

**Comment by leonard-palm-blg** [comment]
@FadyFayezYounan 
I have a very large list of days (1000+) that are in the widget. But I only want to present a window of 5 days. 
I changed the selection mode to `SelectionMode.none()` as you said, but this changes nothing for my case.

The centering is also behaving differently after navigating back and forth from/to this screen. It seems like the `EasyInfiniteDateTimelineController` does not work in a HookWidget. Is there a way to create a hook for this Controller, or maybe pass a Key to the controller?

**Comment by FadyFayezYounan** [comment]
@leonard-palm-blg , Here is an example of how to display only 5 items on the screen.
<details>
  <summary>Show</summary>
import 'package:easy_date_timeline/easy_date_timeline.dart';
import 'package:flutter/material.dart';

class FiveDaysExample extends StatefulWidget {
  const FiveDaysExample({super.key});

  @override
  State<FiveDaysExample> createState() => _FiveDaysExampleState();
}

class _FiveDaysExampleState extends State<FiveDaysExample> {
  final EasyInfiniteDateTimelineController _controller =
      EasyInfiniteDateTimelineController();
  DateTime? _focusDate = DateTime.now();
  @override
  Widget build(BuildContext context) {
    final dayWidth = MediaQuery.sizeOf(context).width / 5;
    return Scaffold(
      appBar: AppBar(
        title: const Text('Easy Date Timeline'),
      ),
      body: Column(
        mainAxisAlignment: MainAxisAlignment.center,
        children: [
          EasyInfiniteDateTimeLine(
            selectionMode: const SelectionMode.autoCenter(),
            controller: _controller,
            timeLineProps: const EasyTimeLineProps(
              separatorPadding: 0.0,
              hPadding: 0.0,
              vPadding: 0.0,
              margin: EdgeInsets.symmetric(vertical: 16.0),
            ),
            firstDate: DateTime(2024),
            focusDate: _focusDate,
            lastDate: DateTime(2024, 12, 31),
            showTimelineHeader: false,
            onDateChange: (selectedDate) {
              setState(() {
                _focusDate = selectedDate;
              });
            },
            dayProps: EasyDayProps(
              width: dayWidth,
              height: dayWidth,
            ),
            itemBuilder: (
              BuildContext context,
              DateTime date,
              bool isSelected,
              VoidCallback onTap,
            ) {
              return InkResponse(
                onTap: onTap,
                child: Padding(
                  padding: const EdgeInsets.all(4),
                  child: Container(
                    width: dayWidth,
                    height: dayWidth,
                    decoration: isSelected
                        ? BoxDecoration(
                            shape: BoxShape.circle,
                            border: Border.all(
                              color: Theme.of(context).colorScheme.primary,
                              width: 3.0,
                            ),
                            boxShadow: [
                              BoxShadow(
                                color: Theme.of(context)
                                    .colorScheme
                                    .primary
                                    .withOpacity(0.2),
                                blurRadius: 0.5,
                              ),
                            ],
                          )
                        : null,
                    child: Opacity(
                      opacity: isSelected ? 1.0 : 0.4,
                      child: Center(
                        child: Column(
                          mainAxisSize: MainAxisSize.min,
                          children: [
                            Text(
                              date.day.toString(),
                            ),
                            Text(
                              EasyDateFormatter.shortDayName(date, "en_US"),
                            ),
                          ],
                        ),
                      ),
                    ),
                  ),
                ),
              );
            },
          ),
          const SizedBox(
            height: 16,
          ),
          Column(
            children: [
              ElevatedButton(
                onPressed: () {
                  _controller.animateToFocusDate();
                },
                child: const Text('Animate To Focus Date'),
              ),
              ElevatedButton(
                onPressed: () {
                  _controller.animateToCurrentData();
                },
                child: const Text('Animate To Current Date'),
              ),
              ElevatedButton(
                onPressed: () {
                  _controller.animateToDate(DateTime(2024, 6, 5));
                },
                child: const Text('Animate To 2024-6-5 '),
              ),
            ],
          ),
        ],
      ),
    );
  }
}

</details>

**Comment by FadyFayezYounan** [comment]
@leonard-palm-blg , here is an example of how to display only 5 items on the screen.

<details>
  <summary>Show</summary>
  
```dart
  import 'package:easy_date_timeline/easy_date_timeline.dart';
import 'package:flutter/material.dart';

class FiveDaysExample extends StatefulWidget {
  const FiveDaysExample({super.key});

  @override
  State<FiveDaysExample> createState() => _FiveDaysExampleState();
}

class _FiveDaysExampleState extends State<FiveDaysExample> {
  final EasyInfiniteDateTimelineController _controller =
      EasyInfiniteDateTimelineController();
  DateTime? _focusDate = DateTime.now();
  @override
  Widget build(BuildContext context) {
    final dayWidth = MediaQuery.sizeOf(context).width / 5;
    return Scaffold(
      appBar: AppBar(
        title: const Text('Easy Date Timeline'),
      ),
      body: Column(
        mainAxisAlignment: MainAxisAlignment.center,
        children: [
          EasyInfiniteDateTimeLine(
            selectionMode: const SelectionMode.autoCenter(),
            controller: _controller,
            timeLineProps: const EasyTimeLineProps(
              separatorPadding: 0.0,
              hPadding: 0.0,
              vPadding: 0.0,
              margin: EdgeInsets.symmetric(vertical: 16.0),
            ),
            firstDate: DateTime(2024),
            focusDate: _focusDate,
            lastDate: DateTime(2024, 12, 31),
            showTimelineHeader: false,
            onDateChange: (selectedDate) {
              setState(() {
                _focusDate = selectedDate;
              });
            },
            dayProps: EasyDayProps(
              width: dayWidth,
              height: dayWidth,
            ),
            itemBuilder: (
              BuildContext context,
              DateTime date,
              bool isSelected,
              VoidCallback onTap,
            ) {
              return InkResponse(
                onTap: onTap,
                child: Padding(
                  padding: const EdgeInsets.all(4),
                  child: Container(
                    width: dayWidth,
                    height: dayWidth,
                    decoration: isSelected
                        ? BoxDecoration(
                            shape: BoxShape.circle,
                            border: Border.all(
                              color: Theme.of(context).colorScheme.primary,
                              width: 3.0,
                            ),
                            boxShadow: [
                              BoxShadow(
                                color: Theme.of(context)
                                    .colorScheme
                                    .primary
                                    .withOpacity(0.2),
                                blurRadius: 0.5,
                              ),
                            ],
                          )
                        : null,
                    child: Opacity(
                      opacity: isSelected ? 1.0 : 0.4,
                      child: Center(
                        child: Column(
                          mainAxisSize: MainAxisSize.min,
                          children: [
                            Text(
                              date.day.toString(),
                            ),
                            Text(
                              EasyDateFormatter.shortDayName(date, "en_US"),
                            ),
                          ],
                        ),
                      ),
                    ),
                  ),
                ),
              );
            },
          ),
          const SizedBox(
            height: 16,
          ),
          Column(
            children: [
              ElevatedButton(
                onPressed: () {
                  _controller.animateToFocusDate();
                },
                child: const Text('Animate To Focus Date'),
              ),
              ElevatedButton(
                onPressed: () {
                  _controller.animateToCurrentData();
                },
                child: const Text('Animate To Current Date'),
              ),
              ElevatedButton(
                onPressed: () {
                  _controller.animateToDate(DateTime(2024, 6, 5));
                },
                child: const Text('Animate To 2024-6-5 '),
              ),
            ],
          ),
        ],
      ),
    );
  }
}
  ```

</details>

**Comment by FadyFayezYounan** [comment]
@leonard-palm-blg I have just updated the package and made some changes to the ItemBuilder. Take a look at it; it may help you. the item builder now has onTap call back responsible for triggering the `onDateChange` callback and animating to the selected date if the `selectionMode` is SelectionMode.autoCenter() or SelectionMode.alwaysFirst(). you can also do not use it an make your own OnTap and use the controller to animate  to date and use set state to update the selected date

**Comment by leonard-palm-blg** [comment]
@FadyFayezYounan Thank you! 
With Version 1.1.1 it works perfectly. 
I also don't have to use the controller anymore for the centering to happen.

PS: I saw you changed `InfiniteItemBuilderCallBack` but not `ItemBuilderCallBack`. Maybe it is a good idea to update both to the same signature.

**Comment by FadyFayezYounan** [comment]
@leonard-palm-blg I am happy that your problem has been resolved. Definitely, I will  update both builders to the same signature., but I need more free time to modify them, i will try to update it today after work
