### ISSUE TITLE
Physics property

### ISSUE THREAD

**Issue by aiman-sartaj** [FadyFayezYounan/easy_date_timeline#32]
Is there any way to add `physics: BouncingScrollPhysics()` property for horizontal calendar scrolling.

**Comment by FadyFayezYounan** [comment]
Now you can use the  `physics `  property with EasyInfiniteDateTimeLine widget.
![physics](https://github.com/FadyFayezYounan/easy_date_timeline/assets/116398331/b317fcd9-a141-4b16-b292-4a1e9bce6a28)
