### ISSUE TITLE
EasyInfiniteDateTimeLine  : Today date is duplicated

### ISSUE THREAD

**Issue by SkilyFrance** [FadyFayezYounan/easy_date_timeline#39]
Hello,
Thanks for this package.

The current day seems to be duplicated on **EasyInfiniteDateTimeLine** : _**DIM. 27 OCT**_ in this case.

`    return EasyInfiniteDateTimeLine(
      locale: 'fr_FR',
      selectionMode: const SelectionMode.alwaysFirst(),
      firstDate: DateTime(2024, 9, 1),
      focusDate: focusDate,
      lastDate: focusDate.add(const Duration(days: 365)),
      onDateChange: onDateChange,
      dayProps: _dayProps(context),
      showTimelineHeader: false,
      headerBuilder: (BuildContext context, DateTime date) => const SizedBox(),
    );`
    
    
Do you have any idea to fix it ?

Thanks !
![Screenshot_20241027-150210](https://github.com/user-attachments/assets/eebdb82e-bb27-42c0-91ec-403efaeb837a)

**Comment by FadyFayezYounan** [comment]
@SkilyFrance , @GregoryHappy Thank you for taking the time to report these issues with the package. I appreciate you bringing them to my attention.
In the meantime, as I work to resolve the issues and publish an update on pub.dev, I would suggest trying to use the package directly from the GitHub repository. This will allow you to use the latest code, which may already contain fixes for the problems you've encountered.

**Comment by GregoryHappy** [comment]
Hello @FadyFayezYounan !
Thanks for your quick answer !

I gave a try with the github version but it seems I have trouble with EasyDateFormatter : "Flutter Doesn't find it / the class doesn't exist anymore ?"

So I came back to the pub.dev version at that time !

Do you have an idea if it's a difficult one to fix and if it's going to take you a lot of time ?

Have a good day !

Grégory

**Comment by FadyFayezYounan** [comment]
Give it a try now from GitHub

**Comment by GregoryHappy** [comment]
Hello @FadyFayezYounan !
Yes ! I test it from github repository and the compilation is now OK for EasyDateFormatter

=> I did 2 screenshots to show you the duplicated date on Sunday 27 October and I think it's related with the fact that when you put lastDay = today you will have in reality on the calender lastday=today-1 like you can see in my second screeshot.

Have a good day !

Grégory

Duplicated date:
-----------------
<img width="349" alt="Capture d’écran 2024-11-01 à 09 43 51" src="https://github.com/user-attachments/assets/a02f78c5-970f-443b-993e-7b948f46a761">

Date of the "today" is not shown: (miss 1 day)
----------------------------------------------
<img width="374" alt="Capture d’écran 2024-11-01 à 09 50 28" src="https://github.com/user-attachments/assets/6616ad4c-eefe-4609-b1c0-93f3b5c56559">

**Comment by Bendix20** [comment]
There was a problem when adding days to a date or calculating the days between two dates. This was done by calculating with durations. But because of time shift some days in some countries can have more or less then 24h. I created a pull request with a fix: https://github.com/FadyFayezYounan/easy_date_timeline/pull/41

**Comment by GregoryHappy** [comment]
Hello @Bendix20 ,
Thanks a lot for the fix, that was not an easy one !  
I just gave a try and it's now ok for me too 👍 ! ( I try to understand what is time shift but it's not clear for me , how do you know or discover that ? )

@FadyFayezYounan Thanks for the merge, i directly use the git repository to have the update !

Have a good day !

Grégory
