### ISSUE TITLE
Any way to limit date range?

### ISSUE THREAD

**Issue by CyMathew** [FadyFayezYounan/easy_date_timeline#5]
Is there way to limit the days to just the current week? Or to be precise, limit it to show only 3 days prior and 3 days in the future, while initialDate = today's date.

I'm guessing it would require customization via itemBuilder but I just wanted to double check.

**Comment by FadyFayezYounan** [comment]
I'll be working on customizing the date picker and I'll make sure to implement and test the behavior thoroughly to ensure it works as expected. Please note that this might take a bit of time, but I'll keep you updated on my progress."

**Comment by CyMathew** [comment]
I forked the repo and made date range changes here:
https://github.com/FadyFayezYounan/easy_date_timeline/compare/master...CyMathew:easy_date_timeline:master

![Screenshot 2023-08-18 at 9 11 31 PM](https://github.com/FadyFayezYounan/easy_date_timeline/assets/10715648/aea9652f-ec42-4769-8b98-4fdda8e50241)
(I set 5 days prior and 6 days in the future for this image)

Please let me know if you'd like me to create a pull request to merge these changes into this repo.

Also, the month picker should probably be hidden when the timeline's date range is limited (I didn't add that). It doesn't make sense for the month to be selectable when the date range has been limited.

**Comment by FadyFayezYounan** [comment]
Great work! I will take a look at the modifications, but have you considered what would happen if the user selects the first date and last date dates with a significant time difference between them? I believe we should check if the first date and the last date are in the same month or not, and based on that, display the month picker.

**Comment by CyMathew** [comment]
That makes sense. But what happens if it spans multiple months? And what should the timeline show when a user selects a new month?

**Comment by FadyFayezYounan** [comment]
After this comment i will update the package, the developer will be able to set a list of days as disabled. What I'm considering for the next step is to add a start date and an end date, as you mentioned, and include the option to select a year. All the dates between the start date and end date will be active, while the remaining dates will be inactive.

**Comment by FadyFayezYounan** [comment]
@CyMathew now you can use the new widget EasyInfiniteDateTimeLine It allows you to define a range of dates with firstDate and lastDate, specify the initial focus with focusedDate, and offers a controller for programmatic interactions

**Comment by CyMathew** [comment]
Thank you! If you no longer need this issue, I can close it

**Comment by FadyFayezYounan** [comment]
@CyMathew You're welcome! I hope the new widget meets your requirements.
