### ISSUE TITLE
way for infinite dates

### ISSUE THREAD

**Issue by jagatrajsingh2000** [FadyFayezYounan/easy_date_timeline#6]
Is there a way to automatically change the month and show date of new next month.

**Comment by FadyFayezYounan** [comment]
@jagatrajsingh2000  now you can use  the new widget (EasyInfiniteDateTimeLine) that allows you to set the start and end dates.  
and offers a controller that can be used to animate or jump to any date

**Comment by FadyFayezYounan** [comment]
Hey @jagatrajsingh2000  Since we haven't heard back in a while, I'm going to close this for now. If anything comes up, please feel free to let me know without hesitation.
