### ISSUE TITLE
Auto center the selected day in the listview

### ISSUE THREAD

**Issue by Matt0550** [FadyFayezYounan/easy_date_timeline#7]
is it possible to center the selected day in the listview?

**Comment by tariqzarif** [comment]
@Matt0550  did you find any solution? I want to center the current day.

**Comment by FadyFayezYounan** [comment]
@Matt0550 , @tariqzarif the package supports now the auto center 
![easy_date_timeline](https://github.com/FadyFayezYounan/easy_date_timeline/assets/116398331/d1013ecb-3b57-4fcb-8f08-178941cbb1a1)
