### ISSUE TITLE
Tomorrow Date Septemper, But Calender Not Showing September Month

### ISSUE THREAD

**Issue by munishinfo** [FadyFayezYounan/easy_date_timeline#9]
Please check this issue

**Comment by FadyFayezYounan** [comment]
Could you please provide a code snippet or screenshot related to your issue? I've tried it myself and didn't notice any problems.

**Comment by FadyFayezYounan** [comment]
Thank you for your feednback. The issue has been resolved, and an update to the library has been made.

**Comment by munishinfo** [comment]
Thanks

Thanks & Regards
Munish kumar B

**Comment by munishinfo** [comment]
Awesome, thanks for the update!

Thanks & Regards
Munish kumar B
